name: Post message to Slack Channel
description: |
  Posts a message to a Slack channel.

  See https://api.slack.com/methods/chat.postMessage for the API reference.
  Requires: `chat:write`
author: '@bitwizeshift'

inputs:
  # Required
  slack-token:
    description: The auth token for the given Slack bot.
    required: true
  channel:
    description: |
      Channel, private group, or IM channel to send message to. Can be an
      encoded ID, or a name. See below for more details.
    required: true

  # Conditionally Required:
  attachments:
    description: |
      A JSON-based array of structured attachments, presented as a URL-encoded
      string.
    required: false
    default: ""
  blocks:
    description: |
      A JSON-based array of structured blocks, presented as a URL-encoded string.
    required: false
    default: ""
  text:
    description: |
      The usage of the text field changes depending on whether you're using
      blocks. If you're using blocks, this is used as a fallback string to
      display in notifications. If you aren't, this is the main body text of
      the message. It can be formatted as plain text, or with mrkdwn.
    required: false
    default: ""

  # Optional
  parse:
    description: |
      Change how messages are treated.

      Messages are formatted as described in the formatting spec. The formatting
      behavior will change depending on the value of parse.

      By default, URLs will be hyperlinked. Set parse to none to remove the
      hyperlinks.

      The behavior of parse is different for text formatted with `mrkdwn` set.
      By default, or when parse is set to none, mrkdwn formatting is
      implemented. To ignore mrkdwn formatting, set parse to full.
    required: false
    default: none
  icon-emoji:
    description: |
      Emoji to use as the icon for this message. Overrides icon_url.

      Example: ":chart_with_upwards_trend:"
    required: false
    default: ""
  icon-url:
    description: |
      URL to an image to use as the icon for this message.

      Example: "http://lorempixel.com/48/48"
    required: false
    default: ""
  username:
    description: Set your bot's user name.
    required: false
    default: ""
  mrkdwn:
    description: |
      Disable Slack markup parsing by setting to false. Enabled by default.
    required: false
    default: "true"
  unfurl-media:
    description: |
      Pass false to disable unfurling of media content.

      Default: true
    required: false
    default: "true"
  unfurl-links:
    description: |
      Pass true to enable unfurling of primarily text-based content.

      Default: true
    required: false
    default: "true"
  thread-ts:
    description: |
      Provide another message's ts value to make this message a reply.
      Avoid using a reply's ts value; use its parent instead.
    required: false
    default: ""

outputs:
  channel:
    description: |
      The property is the ID of the channel, private group or DM channel this
      message is posted in.
  ts:
    description: |
      The unique (per-channel) timestamp representing the thread.

runs:
  using: node20
  main: dist/index.js
